UPDATE [2023-CS-1]
SET GPA = GPA + GPA

SELECT GPA FROM [2023-CS-1]
/*NO EFFECT ON NULL VALUES NOW CHECK IT FOR NULL VALUES ONLY*/
UPDATE [2023-CS-1]
SET GPA = GPA + GPA
WHERE GPA = NULL
SELECT GPA FROM [2023-CS-1]
